#!/usr/bin/env node

//@ts-check
const SRC_DIR = `${__dirname}/config-generator`;
const ZEPTO_SRC = `${SRC_DIR}/libs/zepto.min.js`;
const PURECSS_SRC = `${SRC_DIR}/libs/pure.min.css`;
const PAGE_FILE_SRC = `${SRC_DIR}/_layout.pug`;
const SCRIPT_SRC = `${SRC_DIR}/index.js`;
const STYLESHEET_SRC = `${SRC_DIR}/index.scss`;

const TARGET = `${__dirname}/index.html`;

let fs = require('fs'),
	browserify = require('browserify'),
	pug = require('pug'),
	sass = require('node-sass'),
	watch = require('watch');

	// test babel dependencies
	require('babelify');
	require('babel-plugin-transform-object-rest-spread');
	require('babel-preset-minify');

let defaults = {};
process.argv.indexOf('-w') > 0 || process.argv.indexOf('--watch') > 0 ? buildLive() : build();

function buildSass() {
	return new Promise((resolve, reject) => {
		sass.render({
			file: STYLESHEET_SRC,
			indentedSyntax: false,
			outputStyle: 'compressed',
		}, (err, result) => {
			if (err) return reject(err);
			resolve(result.css);
		});
	});	
}

function buildScript() {
	return new Promise((resolve, reject) => {
		browserify(SCRIPT_SRC)
			.transform("babelify", { presets: ["minify"], plugins: ["transform-object-rest-spread"] })
			.bundle((err, js) => {
				if (err) return reject(err);
				return resolve(js.toString());
			})
	});
}

function buildPug() {
	return new Promise((resolve, reject) => {
		pug.renderFile(PAGE_FILE_SRC, (err, html) => {
			if (err) return reject(err);
			return resolve(html);
		});
	});
}

function readFile(path) { 
	return new Promise((resolve, reject) =>
		fs.readFile(path, 'utf8', (err, ctx) =>
			err ? reject(err) : resolve(ctx)));
}

function build() {
	Promise.all([
		defaults.html || buildPug(),
		defaults.css || buildSass(),
		defaults.js || buildScript(),
		defaults.zepto || readFile(ZEPTO_SRC),
		defaults.purecss || readFile(PURECSS_SRC)
	]).then(([
		html,
		css,
		js,
		zepto,
		purecss
	]) => {
		defaults = { html, css, js, zepto, purecss };
		html = html.replace('__INJECT_JS__', js)
			.replace('__INJECT_CSS__', css)
			.replace('__INJECT_ZEPTO_JS__', zepto)
			.replace('__INJECT_PURECSS__', purecss)
		fs.writeFileSync(TARGET, html);
		console.log('build success!');
	}).catch(err => console.error(err));

}

function buildLive() {
	watch.unwatchTree(SRC_DIR);
	watch.watchTree(SRC_DIR, { interval: 0.5 }, function (path, curr, prev) {
		if (typeof path == "object" && prev === null && curr === null)
			return build(); //First time scan
		let p = String(path);
		if (p.endsWith('.js')) delete defaults.js;
		if (p.endsWith('.pug')) delete defaults.html;
		if (p.endsWith('.scss')) delete defaults.css;
		return build();
	});
}