name: Example Project
src: 
    base: src
    assets: 
        - libs
        - images
    pages: 
        - "*.html"
        - "pages/*.html"
    scripts:
        - "scripts/index.jsx"
    concat:
        "scripts/libs.js":
            - "libs/test1.js"
            - "libs/test2.js"
    styles:
        - "styles/*.scss"
        - "styles/*.sass"
        - "styles/*.css"
dist: 
    base: dist
    clean: true

watch:
    - "src"

hook:
    before_all: "node ../demo-hooks/BEFORE_ALL"
    # after_build: "node ../demo-hooks/AFTER_BUILD"
    # parameters: build_counter:interger

    # async_before_all: "node ../demo-hooks/BEFORE_ALL"
    async_after_build: "node ../demo-hooks/AFTER_BUILD"


processor:
    source_map:
        enable: true
        js: true
        css: true
    browserify:
        transform:
            - name: "babelify"
              options: 
                presets: 
                    - es2015
    watchify:
        delay: 100
        ignoreWatch:
            - '**/node_modules/**'
        poll: false
    sass: true
    less: true
    autoprefixer: true
    browser_sync: 
        enable: true
        server: "dist"
    babel: 
        enable: false
        babelrc: .babelrc
    html_minifier:
        enable: false
        removeComments: true
        collapseWhitespace: true
    ejs: true
    pug: true
    ejs_variables:
        enable: true
        files:
            - src/variables.yaml
    ejs_template_tags: 
        enable: true
        selector: script[type="text/template"]
        